### ISSUE TITLE
Can't compile npm package with 0.0.27 preview

### ISSUE THREAD

**Issue by fredrikekelund** [meteor/windows-preview#24]
I wrapped the npm package `node-xmpp` in a local Meteor package that compiles fine in Meteor 1.0.x, but when I tried with the latest Windows preview there's some problem with compiling node modules, it seems. I get the following output:

	C:\Git\MeteorDataTool\meteor>meteor
	[[[[[ /C/Git/MeteorDataTool/meteor ]]]]]

	=> Started proxy.
	node-xmpp: updating npm dependencies -- node-xmpp...
	=> Started MongoDB.

	module.js:340
	throw err;
	^
	Error: Cannot find module
	'C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-o
	s.windows.x86_32\dev_bundle\bin\node_modules\npm\node_modules\node-gyp\bin\node-
	gyp.js'
	at Function.Module._resolveFilename (module.js:338:15)
	at Function.Module._load (module.js:280:25)
	at Function.Module.runMain (module.js:497:10)
	at startup (node.js:119:16)
	at node.js:906:3
	npm WARN deprecated native-buffer-browserify@2.0.17: please use
	(https://www.npmjs.org/package/buffer) instead. this module was renamed.

	module.js:340
	throw err;
	^
	Error: Cannot find module
	'C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-o
	s.windows.x86_32\dev_bundle\bin\node_modules\npm\node_modules\node-gyp\bin\node-
	gyp.js'
	at Function.Module._resolveFilename (module.js:338:15)
	at Function.Module._load (module.js:280:25)
	at Function.Module.runMain (module.js:497:10)
	at startup (node.js:119:16)
	at node.js:906:3

	module.js:340
	throw err;
	^
	Error: Cannot find module
	'C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.0.37-winr.18\mt-o
	s.windows.x86_32\dev_bundle\bin\node_modules\npm\node_modules\node-gyp\bin\node-
	gyp.js'
	at Function.Module._resolveFilename (module.js:338:15)
	at Function.Module._load (module.js:280:25)
	at Function.Module.runMain (module.js:497:10)
	at startup (node.js:119:16)
	at node.js:906:3
	npm ERR! Windows_NT 6.2.9200
	npm ERR! argv
	"C:\\Users\\Fredrik\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.0.37-winr
	.18\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe"
	"C:\\Users\\Fredrik\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.0.37-winr
	.18\\mt-os.windows.x86_32\\dev_bundle\\bin\\node_modules\\npm\\bin\\npm-cli.js"
	"install" "node-xmpp@1.0.0-alpha2"
	npm ERR! node v0.10.33
	npm ERR! npm  v2.1.17
	npm ERR! code ELIFECYCLE

	npm ERR! node-stringprep@0.5.4 install: `node-gyp rebuild`
	npm ERR! Exit status 8
	npm ERR!
	npm ERR! Failed at the node-stringprep@0.5.4 install script 'node-gyp rebuild'.
	npm ERR! This is most likely a problem with the node-stringprep package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls node-stringprep
	npm ERR! There is likely additional logging output above.

	=> Errors prevented startup:

	   While building package node-xmpp:
	   error: couldn't install npm package

	=> Your application has errors. Waiting for file change.

**Comment by stubailo** [comment]
Good catch! Fixing this now, should be working in the next preview. I'll post here when it's up.

**Comment by stubailo** [comment]
This should be fixed now, try the newest preview: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows
